language: node_js
node_js:
  - "10"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli
  - npm install .

script:
  - ng build --prod --aot --base-href="https://firewut.github.io/svg_subway/" --deploy-url="https://firewut.github.io/svg_subway/" --optimization=false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/svg-subway
  target_branch: gh-pages
  on:
    branch: master